export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  INTERVIEW_SETUP: '/interview/setup',
  INTERVIEW_VOICE: '/interview/voice',
  INTERVIEW_RESULT: '/interview/result',
  INTERVIEW_HISTORY: '/interview/history',
  REPORTS: '/reports',
  PROFILE: '/profile',
  RESUME_UPLOAD: '/resume/upload',
  RESUME_ANALYSIS: '/resume/analysis',
};
